Fix expression that cannot be used as a function
As reported in [Debian bug #1075273], starting with g++ 14, the build
fails with the following error (that was missing from the semi
automated report):

	/<<PKGBUILDDIR>>/src/FindBreakpoints.hpp:786:38: error: expression cannot be used as a function
	  786 |     return this->m_solid_stretch_size();
	      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~

Looking at other instances of the m_solid_stretch_size attribute, the
use of the expression as a function seems to be erroneous and the
intent seems to have been to return the plain integer number instead.

[Debian bug #1075273]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1075273

Signed-off-by: Étienne Mollier <emollier@debian.org>